# ========================
# GAPS
# ========================
bind = SUPER+Shift,equal,incgaps,1
bind = SUPER+Shift,minus,incgaps,-1
bind = SUPER+Shift,r,togglegaps

# ========================
# SWITCH LAYOUT
# ========================
bind = SUPER,n,switch_layout

# ========================
# SCROLLER LAYOUT
# ========================
bind = SUPER,e,set_proportion,1.0
bind = SUPER,x,switch_proportion_preset

# ========================
# RESIZE DAN MOVE WINDOW
# ========================
bind = Ctrl+Shift,Up,movewin,+0,-50
bind = Ctrl+Shift,Down,movewin,+0,+50
bind = Ctrl+Shift,Left,movewin,-50,+0
bind = Ctrl+Shift,Right,movewin,+50,+0

bind = Ctrl+Alt,Up,resizewin,+0,-50
bind = Ctrl+Alt,Down,resizewin,+0,+50
bind = Ctrl+Alt,Left,resizewin,-50,+0
bind = Ctrl+Alt,Right,resizewin,+50,+0
