# ========================
# MENU DAN TERMINAL
# ========================
bind = SUPER,space,spawn,rofi -show drun
bind = SUPER,Return,spawn,foot
bind = SUPER,d,spawn,rofi -show run

# ========================
# RELOAD CONFIG
# ========================
bind = SUPER,r,reload_config

# ========================
# EXIT
# ========================
bind = SUPER,Shift,e,quit
