# ========================
# MOUSE BINDINGS
# ========================
mousebind = SUPER,btn_left,moveresize,curmove
mousebind = SUPER,btn_right,moveresize,curresize
mousebind = NONE,btn_middle,togglemaximizescreen,0

# ========================
# AXIS BINDINGS (Scroll wheel)
# ========================
axisbind = SUPER,UP,viewtoleft_have_client
axisbind = SUPER,DOWN,viewtoright_have_client
