# ========================
# SWITCH WINDOW FOCUS (Navigasi)
# ========================
bind = SUPER,h,focusdir,left
bind = SUPER,j,focusdir,down
bind = SUPER,k,focusdir,up
bind = SUPER,l,focusdir,right

bind = SUPER,Left,focusdir,left
bind = SUPER,Down,focusdir,down
bind = SUPER,Up,focusdir,up
bind = SUPER,Right,focusdir,right

bind = SUPER,Tab,focusstack,next

# ========================
# SWAP WINDOW (Tukar posisi jendela)
# ========================
bind = SUPER+Shift,Up,exchange_client,up
bind = SUPER+Shift,Down,exchange_client,down
bind = SUPER+Shift,Left,exchange_client,left
bind = SUPER+Shift,Right,exchange_client,right
