# ========================
# PINDAH TAG (View)
# ========================
bind = SUPER,1,view,1,0
bind = SUPER,2,view,2,0
bind = SUPER,3,view,3,0
bind = SUPER,4,view,4,0
bind = SUPER,5,view,5,0
bind = SUPER,6,view,6,0
bind = SUPER,7,view,7,0
bind = SUPER,8,view,8,0
bind = SUPER,9,view,9,0

# ========================
# MEMINDAHKAN CLIENT KE TAG
# ========================
bind = Alt,1,tag,1,0
bind = Alt,2,tag,2,0
bind = Alt,3,tag,3,0
bind = Alt,4,tag,4,0
bind = Alt,5,tag,5,0
bind = Alt,6,tag,6,0
bind = Alt,7,tag,7,0
bind = Alt,8,tag,8,0
bind = Alt,9,tag,9,0

# ========================
# NAVIGASI TAG DENGAN PANAH
# ========================
bind = SUPER,Left,viewtoleft,0
bind = SUPER,Right,viewtoright,0
bind = SUPER+Shift,Left,tagtoleft,0
bind = SUPER+Shift,Right,tagtoright,0
