# ========================
# WINDOW OPERATIONS
# ========================
bind = SUPER,q,killclient
bind = SUPER,Shift,q,killclient

bind = SUPER,f,togglefullscreen
bind = SUPER,Shift,f,togglefakefullscreen
bind = SUPER,v,togglefloating
bind = SUPER,m,togglemaximizescreen
bind = SUPER,o,toggleoverview
bind = SUPER,g,toggleglobal
bind = SUPER,z,toggle_scratchpad

# ========================
# MINIMIZE
# ========================
bind = SUPER,i,minimized
bind = SUPER,Shift,i,restore_minimized
