#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV 
bspc config border_width        4
bspc config window_gap          8
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config normal_border_color         "#51576d"
bspc config active_border_color         "#d5a4b5"
bspc config focused_border_color        "#d5a4b5"
bspc config presel_feedback_color       "#d5a4b5"
bspc config urgent_border_color         "#d5a4b5"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating

feh --bg-scale ~/.config/bspwm/walpapper/wallhaven-3led2d.jpg &
$HOME/.config/polybar/mybar/run.sh
