# ========================
# AUTOSTART
# ========================
exec-once = waybar -c ~/.config/mango/waybar/config.jsonc -s ~/.config/mango/waybar/style.css
exec-once = swaybg -i /home/aka/Downloads/wallhaven-oggerl.jpg
