# ==============================================
# MANGO CONFIGURATION - FreeBSD (Main File)
# ==============================================

# source semua konfigurasi
source = ~/.config/mango/autostart.conf
source = ~/.config/mango/rules/tagrules.conf
source = ~/.config/mango/keybindings/menu.conf
source = ~/.config/mango/keybindings/navigation.conf
source = ~/.config/mango/keybindings/windows.conf
source = ~/.config/mango/keybindings/tags.conf
source = ~/.config/mango/keybindings/layout.conf
source = ~/.config/mango/mouse.conf
